### PR TITLE
Integrate ECC-extended HCI.

### PR DESCRIPTION
**Pull request by LuigiGhionda**
This PR extends HCI modules of the streamer with ECC and add memory-mapped registers to collect statistics on occurred fault

### CODE REVIEW

**Comment by LuigiGhionda** [comment]
I created a separate branch from the "hci-v2.1" branch and set it as the target of the PR because the "astral" branch has diverged. I hope this is ok

**Review by yvantor — COMMENTED** [review]
Approved. If you did not do it yet, I would suggest to run the regression script you find under `scripts` for a general sanity check. Also write to Maurus to compare because he recently found some bugs in the sw test. Let me know if the two steps above are complete and then we can merge!

**Comment by yvantor** [comment]
> I created a separate branch from the "hci-v2.1" branch and set it as the target of the PR because the "astral" branch has diverged. I hope this is ok

Yes, it is more than fine!

**Comment by LuigiGhionda** [comment]
> Approved. If you did not do it yet, I would suggest to run the regression script you find under `scripts` for a general sanity check. Also write to Maurus to compare because he recently found some bugs in the sw test. Let me know if the two steps above are complete and then we can merge!

Yes, I ran the regression script, including Maurus's modifications. It was only necessary to slightly increase the timeout time for each test from 100s to 120s, which should be related to the overhead of reading the error-counting registers.

**Comment by Lynx005F** [comment]
Can you also update the `scripts/non-regression_test.sh` do reflect your changes?
E.g. run it with ECC enabled and disabled, update timeout etc.

**Comment by LuigiGhionda** [comment]
> Can you also update the `scripts/non-regression_test.sh` do reflect your changes? E.g. run it with ECC enabled and disabled, update timeout etc.

Done. Thank you for the reminder

**Comment by Lynx005F** [comment]
Based of this branch I made a version that only does the ECC Encode / Decode at the very outside:
https://github.com/Lynx005F/redmule/commits/itemm/hci-v2.1-ecc-outside/

Thanks to your regression script I could test it works right away ;), I think I will most likely rebase the other redundancy-related changes onto it first and then see if I can find ways to protect the streamer control and W path on top of it.

**Comment by Lynx005F** [comment]
Ah I see you used the same approach now as well, so I can rebase the other redundancy stuff on top of it. Neat!

**Review by yvantor — APPROVED** [review]

**Comment by yvantor** [comment]
@LuigiGhionda is this also the version currently used in PULP cluster?

**Comment by yvantor** [comment]
> @LuigiGhionda is this also the version currently used in PULP cluster?

I checked. Merging!

**Comment by LuigiGhionda** [comment]
> @LuigiGhionda is this also the version currently used in PULP cluster?

Yes, exactly (late confirmation)

**Pull request merged**
